server:
  port: 8083

spring:
  application:
    name: 'server-internal-api'

  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.use_sql_comments: true

logging:
  level:
    io.devfactory: debug
